Touch now works on timeline bar.
_handleTouchMove was an old function that was removed (commit 1b1dea57276f36186c455091e01ca0156346e588).

Replacing with _onTouchMove allows the touch to work on the timeline.

To experience this bug:
1. Go to http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases
2. Using touch (or an emulation in Chrome), touch the timeline bar (make sure it's touch, not a mouse).
3. Uncaught TypeError: timeline._handleTouchMove is not a function.